### ISSUE TITLE
Problem with detected cards

### ISSUE THREAD

**Issue by TiSa1988** [mzakharo/birdnetapp#1]
Hey there,

I'm trying to install birdnetapp on my raspberry pi for I find the solution with Telegram and InfluxDB very interessting! I had some problems, which I was able to solve (install missing modules, load secrets.py-file), but unfortunately my very rudmientary skills in python and the alsaaudio module are not good enough for the following problem. It seems that birdnetapp is not able to find my microphone and use it. When I try to start the main.py it stops with the following error:

> INFO:birdnetapp:detected cards ['Headphones', 'Microphones', 'vc4hdmi0', 'vc4hdmi1'] configuring: Device
Traceback (most recent call last):
  File "/home/pi/birdnetapp/main.py", line 2, in <module>
    main()
  File "/home/pi/birdnetapp/birdnetapp/__init__.py", line 276, in main
    stream.open()
  File "/home/pi/birdnetapp/birdnetapp/__init__.py", line 190, in open
    card_i = cards.index(self.card)
ValueError: 'Device' is not in list

How can I solve this? 

Thanks in advance and kind regards!

**Comment by TiSa1988** [comment]
Well, I just realized that I have to specify "card" in config.py. Sorry for the inconvenience...!

**Comment by mzakharo** [comment]
Hi, please let  me know what issues (and missing modules) you had encountered setting this up, and I will add these to the REAMDE.

**Comment by TiSa1988** [comment]
Hi!
Although they are in the requirements.txt, I had to install pyalsaaudio (and previously libasound2-dev), influxdb-client and pyTelegramBotAPI individually. I didn't overlook the requirements install session, so I cannot tell if there has been an error with these modules during that install... I'm trying to finalize the setup in the coming days, then I'll know if I did the previous steps of the readme correctly :)

**Comment by TiSa1988** [comment]
Alright, I made the birdnetapp run. The Microphone was inside and thus there were no birdsounds. The App ran about twenty seconds and ended with this error:

> INFO:birdnetapp:detected cards ['Headphones', 'Microphones', 'vc4hdmi0', 'vc4hdmi1'] configuring: Microphones
INFO:birdnetapp:started
Traceback (most recent call last):
  File "/home/pi/birdnetapp/main.py", line 2, in <module>
    main()
  File "/home/pi/birdnetapp/birdnetapp/__init__.py", line 278, in main
    runner(args, stream)
  File "/home/pi/birdnetapp/birdnetapp/__init__.py", line 252, in runner
    assert len(futures) < 10 , "Processing not keeping up with incoming data"
AssertionError: Processing not keeping up with incoming data

For your information, I have an Raspberry Pi 4B with 2gb RAM. Could this model be too slow for this app?

I then ran the app again and played a ring necked pheasant to see, if it is able to detect it. And it was. I still got the following error:

> INFO:birdnetapp:detected cards ['Headphones', 'Microphones', 'vc4hdmi0', 'vc4hdmi1'] configuring: Microphones
INFO:birdnetapp:started
INFO:birdnetapp:Ring-necked Pheasant /home/pi/birdNet/Ring-necked Pheasant/22-07-23_08-32-21.mp3 conf: 0.9997
INFO:birdnetapp:Ring-necked Pheasant /home/pi/birdNet/Ring-necked Pheasant/22-07-23_08-32-24.mp3 conf: 0.9998
Traceback (most recent call last):
  File "/home/pi/birdnetapp/main.py", line 2, in <module>
    main()
  File "/home/pi/birdnetapp/birdnetapp/__init__.py", line 278, in main
    runner(args, stream)
  File "/home/pi/birdnetapp/birdnetapp/__init__.py", line 255, in runner
    res = f.result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 433, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/pi/birdnetapp/birdnetapp/__init__.py", line 222, in process
    return upload_result(ts, fname, SAVEDIR, res, args.min_confidence, args.dry)
  File "/home/pi/birdnetapp/birdnetapp/__init__.py", line 137, in upload_result
    df = query_api.query_data_frame(query)
  File "/usr/local/lib/python3.9/dist-packages/influxdb_client/client/query_api.py", line 126, in query_data_frame
    _generator = self.query_data_frame_stream(query, org=org, data_frame_index=data_frame_index, params=params)
  File "/usr/local/lib/python3.9/dist-packages/influxdb_client/client/query_api.py", line 146, in query_data_frame_stream
    response = self._query_api.post_query(org=org, query=self._create_query(query, self.default_dialect, params),
  File "/usr/local/lib/python3.9/dist-packages/influxdb_client/service/query_service.py", line 281, in post_query
    (data) = self.post_query_with_http_info(**kwargs)  # noqa: E501
  File "/usr/local/lib/python3.9/dist-packages/influxdb_client/service/query_service.py", line 307, in post_query_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.9/dist-packages/influxdb_client/_sync/api_client.py", line 343, in call_api
    return self.__call_api(resource_path, method,
  File "/usr/local/lib/python3.9/dist-packages/influxdb_client/_sync/api_client.py", line 173, in __call_api
    response_data = self.request(
  File "/usr/local/lib/python3.9/dist-packages/influxdb_client/_sync/api_client.py", line 388, in request
    return self.rest_client.POST(url,
  File "/usr/local/lib/python3.9/dist-packages/influxdb_client/_sync/rest.py", line 293, in POST
    return self.request("POST", url,
  File "/usr/local/lib/python3.9/dist-packages/influxdb_client/_sync/rest.py", line 243, in request
    raise ApiException(http_resp=r)
influxdb_client.rest.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Date': 'Sat, 23 Jul 2022 06:32:23 GMT','Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'trace-id': 'e769ffcc187e1373', 'trace-sampled':'false', 'vary': 'Accept-Encoding', 'x-platform-error-code': 'not found', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains', 'X-Influxdb-Request-ID': '27f7e54fed205cc16c835cc96135e5c8', 'X-Influxdb-Build': 'Cloud'})
HTTP response body: b'{"code":"not found","message":"failed to initialize execute state: could not find bucket \\"main\\""}'

I defined the bucket in my config.py, but the app still tried to put in a "main" bucket on influxdb. I then opened a "main" bucket but I wasn't able to start the app again since the first run, because it always gives me the first error that the processing could not keeping up with incoming data. I didn't get any telegram message from this run.
What do these errors say? Can I do something to make the app run or is my 2gb system not fast enough for BirdNET-Analyzer?

**Comment by mzakharo** [comment]
Can you please post your config.py? 

I assume you installed `tflite-runtime` and not `tensorflow` when setting up birdnetAnalyzer. Also, are you running a 64-bit OS?
Also, can you please send logs (if any) from the BirdNetAnalyzer server ?

**Comment by TiSa1988** [comment]
My config.py:
> #Mic settings
>
>#PS-Eye
>RATE = 48000
CHANNELS = 2
CARD = 'Device'
CHUNK = RATE * 1 # 1 second buffer
>
>#Files saved here
SAVEDIR = '/home/pi/birdNet'
>
>#Number of most recent files to keep per bird
KEEP_FILES = 300
>
>#whether store longterm results in wav or mp3
EXPORT_FORMAT = '.mp3'
>
>#how long to wait before sending a notification
NOTIFICATION_DELAY_SECONDS = 60*5
>
>#birdNET settings
>
>#Note: recording length has impact on conf_thresh
#longer recording could lower CONF_THRESH to achieve the same detection rate
RECORD_SECONDS = 6
CONF_TRHRESH = 0.55
LAT=53.XXXX
LON=8.XXXX
OVERLAP = 0
>
>#birdNet server
HOST='127.0.0.1'
PORT = 8080
>
>#influx
ORG = "Altburgbirding"
BUCKET = "Altburgbirding"
>
>SEEN_TIME = '14d'

I installed `tflite-runtime`, yes.
I run the following os with 64 bit:
>    Static hostname: raspberrypi
         Icon name: computer
  Operating System: Debian GNU/Linux 11 (bullseye)
            Kernel: Linux 5.15.32-v8+
      Architecture: arm64

Here is the log of the BirdNET-Analyzer server.py:

> {'lat': 53.XXX, 'lon': 8.XXX, 'num_results': 3, 'overlap': 0, 'week': 29}
Analyzing /tmp/tmp77k2zp47.wav
Finished /tmp/tmp77k2zp47.wav in 0.89 seconds
####################  2022-07-23 17:18:11.059596  ####################
{'lat': 53.XXX, 'lon': 8.XXX, 'num_results': 3, 'overlap': 0, 'week': 29}
Analyzing /tmp/tmpno0ixxjt.wav
Finished /tmp/tmpno0ixxjt.wav in 0.87 seconds
####################  2022-07-23 17:18:12.017010  ####################
{'lat': 53.XXX, 'lon': 8.XXX, 'num_results': 3, 'overlap': 0, 'week': 29}
Analyzing /tmp/tmpz3v3xk58.wav
Finished /tmp/tmpz3v3xk58.wav in 0.88 seconds
####################  2022-07-23 17:18:12.971397  ####################
{'lat': 53.XXX, 'lon': 8.XXX, 'num_results': 3, 'overlap': 0, 'week': 29}
Analyzing /tmp/tmpbgk9lg_x.wav
Finished /tmp/tmpbgk9lg_x.wav in 0.88 seconds
####################  2022-07-23 17:18:13.932491  ####################
{'lat': 53.XXX, 'lon': 8.XXX, 'num_results': 3, 'overlap': 0, 'week': 29}
Analyzing /tmp/tmpl79xbhnf.wav
Finished /tmp/tmpl79xbhnf.wav in 0.89 seconds
####################  2022-07-23 17:18:14.892353  ####################
{'lat': 53.XXX, 'lon': 8.XXX, 'num_results': 3, 'overlap': 0, 'week': 29}
Analyzing /tmp/tmp2_w8u94_.wav
Finished /tmp/tmp2_w8u94_.wav in 0.88 seconds

When I start the server.py, I do it with screen, so I am able to start the birdnetapp while the server.py is still running:
`screen python3 server.py`
I don't know if this is the right solution, is there another way to start the server.py and afterwards the birdnetapp? 
Thank you for your help!

**Comment by mzakharo** [comment]
screen is not an issue (tried it myself, works fine). Also your logs and config look good.  `birdnetapp` sends 6 seconds of buffer to process every 3 seconds, so any processing time of > 3 seconds is an issue. Your logs show <1 second. no problems there.

 I see an issue where on cold start, birdnetAnalyzer would take closer to 60 seconds to produce the first result on my RPI-3, which causes the same error you are seeing,  As a quick solution to try, is to just restart birdnetapp without touching birdnetAnalyzer server  upon this error, and see if it continues to work normally. 

As for starting the app and the server in the background, there are systemd service configs in the root of repo:

(Note: systemd service runs as root, so make sure you `sudo pip3 install -r requirements.txt`

```
sudo cp birdnet_server.service  /lib/systemd/system/
sudo systemctl daemon-reload
sudo systemctl enable birdnet_server.service 
sudo systemctl start birdnet_server.service 
sudo systemctl status birdnet_server.service 
```

**Comment by mzakharo** [comment]
Also, if the problem persists, please  `git pull`  to get latest updates of the `birdnetapp`  and  post the log here when run with `python3 main.py --debug`

**Comment by mzakharo** [comment]
And one more thing that could be an issue: `RATE` and `CHANNELS` setting might not be compatible with your microphone/card. To test,  run
 ```
 arecord -l 
 ```
to see a list of devices, then in my case it returns
```
**** List of CAPTURE Hardware Devices ****
card 1: Device [USB Audio Device], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```
so I would type:
```
arecord -f cd --device="hw:1,0" --rate 48000 --channel 2 foo.wav
```
If this command records audio successfully, then it is not an issue, however, watch if it prints something like this: 
```
Warning: rate is not accurate (requested = 48000Hz, got = 44100Hz)
         please, try the plug plugin 
```
Then you would need to adjust config.py accordingly

**Comment by mzakharo** [comment]
Nevermind the `arecord` checks. I added  Mic setting configuration error checks in the code.  Just get the latest code from  `birdnetapp`  repo, and run `python3 main.py`

**Comment by TiSa1988** [comment]
Nice, now it works! I get data from the detected birds into my InfluxDB. Unfortunately, I don't get a message via telegram. At first, I made a channel with my bot in it and put the channel_id into the chatid value. Now I changed it into a chatid (of a group chat where the Bot and me is in) and revoke the token of the bot but I still don't get a message from telegram. There is no error, so I really don't know why it doesn't work... I'm still happy and will run the app during the coming night! Thank you for your help!

**Comment by mzakharo** [comment]
Please note, telegram messages are delayed by about 5 minutes after the bird stops tweeting,  this allows collection of 'best'  audio sample, not just first sample, to be sent over telegram. You can control this delay in config.py (NOTIFICATION_DELAY_SECONDS) or on command line `python3 main.py --notification_delay 0`

Also, you wont get a telegram notification unless the bird is new.  all 'seen' birds in a time window will not trigger a telegram.  app queries influx to see if bird is already there for a specified time window. You can control this via a setting in config.py : `SEEN_TIME`  -> default is 2 weeks, you can set it to whatever you want.

Do you get a message printed like this example? 
```INFO:birdnetapp:sending telegram message for Northern Cardinal```

If  so, to debug telegram specifically, I just pushed some test-code. Please  get the latest code for `birdnetapp`, and run the following command from `birdnetapp` folder: 
```
PYTHONPATH=. python3 tests/test_telegram.py
```
If all goes well, you should get a telegram message about a Cardinal.

P.S.  Assuming you cloned the repo with lfs , if not, do `git lfs pull`, as it needs `example/cardinal.wav` to be about 1.3M

**Comment by TiSa1988** [comment]
Yepp, you were right. Telegram messages started a few minutes later and keep coming since. But it doesn't matter if the species was already detected today.. I have no idea why, the config.py has the 14d value in it (see above). Do you have any ideas? 
Except for this issue, I'm very happy with the results! Thank you very much for helping me setting it up!

**Comment by mzakharo** [comment]
hm, I am unable to reproduce your telegram messages spam.  It works fine with my setup.  One thing to try is see what this query returns in your influx instance . It should contain already seen birds.
```
                import "influxdata/influxdb/schema"
                schema.fieldKeys(
                    bucket: "main",
                    predicate: (r) => r["_measurement"] == "birdnet",
                    start: -14d,
                )

```

**Comment by TiSa1988** [comment]
Well, I didn't overthing the influxdb query process 'cause I am quite happy with the current state to get telegram messages and all my data to my InfluxDB _Cloud_ instance... There's no local influxdb yet, this is why the query doesn't work, right? Sorry for that! I'm going to try it in the next days! Thanks again for your help! :)

**Comment by mzakharo** [comment]
It works for me with Influx2 cloud instance from (https://cloud2.influxdata.com/signup).  There should be no difference between cloud and local setup. 

P.S. One thing I changed in the latest code is move  the `bucket` name and influx `org` into the `secrets.py` file, since those parameters seem to be all related.

**Comment by TiSa1988** [comment]
I didn't have the time to update my pi the past week. Just to let you know, now that I have, it all works out!
